### ISSUE TITLE
Appengine & Ubuntu failed to compile due to undefined: client.GetMetadata

### ISSUE THREAD

**Issue by edwindvinas** [jpfielding/gorets#32]
Hi,

I tried to run Gorets both in Appengine and Ubuntu but I get an error which seems like a missing function? Kindly let me know what you think I missed to do? By the way, I used the given sample code in the main readme page of gorets; do I need to update anything on the given sample code?

./gorets.go:76: undefined: client.GetMetadata
./gorets.go:80: unknown client.MetadataRequest field 'Id' in struct literal
./gorets.go:93: undefined: client.COUNT_AFTER
./gorets.go:97: undefined: client.Search
./gorets.go:111: too many arguments to conversion to client.GetObject: client.GetObject(session, ctx, client.GetObjectRequest literal)
./gorets.go:127: too many arguments to conversion to client.GetObject: client.GetObject(session, ctx, client.GetObjectRequest literal)

Thanks a lot!
-Edwin

**Comment by jpfielding** [comment]
master /README.md was not up to date with the latest from master.  ive updated it to address the issues,   gorets/cmds/client/client.go is often the most up to date.  i may need to consolidate those somehow to make sure the example is compiled.

**Comment by edwindvinas** [comment]
Thank you very much!
