### ISSUE TITLE
Will gorets run on the heroku?

### ISSUE THREAD

**Issue by briviere** [jpfielding/gorets#33]
I know this is not an issue, it actually a question?  Is anyone using this gorets client on Heroku?

thanks

Brian

**Comment by kelcecil** [comment]
We've deployed gorets to AWS and GCE successfully, so I can't think of a reason that you couldn't use it on Heroku.

**Comment by jpfielding** [comment]
not sure why it wouldnt, if you try it, let us know on gophers.slack.com#gorets
