### ISSUE TITLE
cannot find package "context" when building

### ISSUE THREAD

**Issue by consulthys** [jpfielding/gorets#37]
When trying to build the `gorets` library with Go 1.6, I get the following error.
```
rets/get.go:7:2: cannot find package "context" in any of:
	/Users/me/workspaces/go/src/github.com/jpfielding/gorets/vendor/context (vendor tree)
	/usr/local/go/src/context (from $GOROOT)
	/Users/me/workspaces/go/src/context (from $GOPATH)
make: *** [test] Error 1
```

If I replace the `"content"` import by `"golang.net/x/net/context"` then it works.

PS: This is a great library, by the way. Kudos JP!!

**Comment by kelcecil** [comment]
The context library was promoted to the stdlib in Go 1.7 which is what we're using in production. Can you upgrade to using Go 1.7? It was very straight forward for us.

**Comment by consulthys** [comment]
Thanks @kelcecil for getting back to me so quickly. That might well solve the issue, I'll try and report here asap.

**Comment by consulthys** [comment]
That was definitely the issue. Upgrading to Go 1.7 did the trick. Thanks much!

**Comment by consulthys** [comment]
Thanks again for your help. 

Some kudos to you guys here: https://discuss.elastic.co/t/announcement-retsbeat-released/59545

;-)

**Comment by kelcecil** [comment]
No problem! Thank you for the shout out! Much appreciated!
