### ISSUE TITLE
Problem to Connect to http://testing.reso.org

### ISSUE THREAD

**Issue by leonardoo** [jpfielding/gorets#52]
hi,

im trying to connect to http://testing.reso.org but i have a problem, always give me 401 - Unauthorized: Access is denied due to invalid credentials.

also i ran gorets explore but get the same message
![screenshot_2018-04-10_08-28-31](https://user-images.githubusercontent.com/3915706/38559656-3b99325c-3c99-11e8-830b-5e45b6644561.png)

i ran unsing the following credentials

Login URL:  http://testing.reso.org:9080/Login.asmx/Login
User Name:  leonardoo
Password:   leonardoo
User Agent: ResoTestingClient/1.0
User Agent Password:    ResoCompl
RETS Version:   RETS/1.7.2

also i did a test using https://retsmd.com/ and it work ok and got all the metadata

Thanks

**Comment by jpfielding** [comment]
so this is an issue with their server requesting both basic and digest, but only accepting digest.  in other interealty implementations that we use, if they request both, gorets just picks one and goes with it.  these work in production, against interealty, this may be a misconfiguration on the test servers end.  im going to look into http rfc's and see what the proper course of action would be in this case.

**Comment by jpfielding** [comment]
got a fix in the applies the auths in order and overwrites with digest.  this also kind of sucks.  i also tried applying both digest and basic, but this server only accepts digest.  probably not something we should commit to long term, but it will breathe for today.

**Comment by sredXNY** [comment]
hello @jpfielding , sorry for reopen this issue again, but it seems like this fix then broke the ability to connect with the others Rets servers, I explain: before this fix I was able to connect to others servers with no problem and now I can connet to the test rets server but no with the others.

The exact error message that I am getting is: `failed to read urls`
Also, I tested with Rets Explorer and the result was the same, see here https://screenshots.firefox.com/5IYFQM1TYasnDAWO/localhost

**Comment by jpfielding** [comment]
do you have any detail on which rets servers (vendors or specific mls)
could connect before but cannot connect now?

**Comment by greenenergy** [comment]
If I may add my $.25 - I also cannot connect to my RETS server.  The server I'm connecting to is:

 "http://data.crea.ca/Login.svc/Login"

**Comment by jpfielding** [comment]
Perfect, specific vendor info helps, is this a new issue since the auth
change?

**Comment by jpfielding** [comment]
given the only case this change originally solved was a contrived example rets server, and every other connection my team connects to works in the previous setup im reverting the change until we have more data and a clearer path.

**Comment by sredXNY** [comment]
@jpfielding  what information can I provide you to give you more context on this issue? I've been trying to connect to IMLS, it wrks for the rets testing server but nothing else

**Comment by jpfielding** [comment]
Best thing would be the wirelog of your requests.  Short of that, the
settings youre using (not including user/pwd if it's not test server or
publicly available).

**Comment by greenenergy** [comment]
Hi JP -- were you going to roll the change back? You said you were going to revert it 4 days ago.

specifically, I have to go back to commit ac8704c406a5113a9f8e35399b3a94a5a844becc for logins to work.

**Comment by jpfielding** [comment]
yeah, sorry, was waiting for more info on other servers but never heard
anything.  rolling it back now.

**Comment by sredXNY** [comment]
@jpfielding  hello! very sorry for the delay but until today I had the time to get the wirelogging for this. Here I attach the not working logg, I also have the working logging for the same rets user if you think that it's needed just let me know, but for now I will let here the not-working one 
[not working.log](https://github.com/jpfielding/gorets/files/1968459/not.working.log)

**Comment by jpfielding** [comment]
looking at this file, it appears you've never set your user/pwd.  the www digest response is blank.  if this was before i reverted the change for the test server, it probably works again.
