### ISSUE TITLE
Commit 5696c4cd19232baa0e8a414fa811bb4a47e57033 breaks login

### ISSUE THREAD

**Issue by greenenergy** [jpfielding/gorets#55]
Not sure what it was that changed in this particular commit (labelled `issue #52 where intereality server challenges both basic and digest, but only accepts digest`) but it broke my ability to log into my RETS server.

This is observable in the gorets tool, when running search:

    search: unable to parse capabilites response: failed to read urls

**Comment by greenenergy** [comment]
I'm going to close this issue since issue 52 does cover it.

**Comment by greenenergy** [comment]
Nevermind - I can't reopen 52, so here we go.

**Comment by jpfielding** [comment]
i reverted that.  it was a bad idea to change working code for a test server.  i feel sufficiently shamed.
