### ISSUE TITLE
Update transaction - (10.x)

### ISSUE THREAD

**Issue by jpfielding** [jpfielding/gorets#7]
does any server actually support this?  if so, testing would be a nightmare.

**Comment by consulthys** [comment]
If needed, I can help test this out as I've gained some good knowledge of how RETS Update works when implementing it the [rets-client](https://github.com/consulthys/rets-client) library (for Node.js)

**Comment by jpfielding** [comment]
i mostly need creds with access to update.  its not something i have use for at the moment but if you need it and want to do some work on it and submit a patch id be happy to look it over / merge it.
